[package]
name = "bit-set"
version = "0.2.0"
authors = ["Alexis Beingessner <a.beingessner@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A Vec of bits"
repository = "https://github.com/contain-rs/bit-set"
homepage = "https://github.com/contain-rs/bit-set"
documentation = "https://contain-rs.github.io/bit-set/bit_set"
keywords = ["data-structures"]
readme = "README.md"

[dev-dependencies]
rand = "0.3"

[dependencies]
bit-vec = "0.4"
